[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-fps", "60", "--transition-type", "center"]
set = true

[templates.ghostty]
input_path = '~/.config/matugen/templates/ghostty'
output_path = '~/.config/ghostty/themes/matugen-colors'
post_hook = 'pkill -SIGUSR2 ghostty'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/matugen-colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/matugen-colors.css'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.config/hypr/source/matugen-colors.conf'
post_hook = 'hyprctl reload > /dev/null'

[templates.millennium]
input_path = '~/.config/matugen/templates/millennium.css'
output_path = '~/.steam/steam/steamui/skins/Material-Theme/css/main/colors/matugen.css'
post_hook = '~/.config/hypr/scripts/restart_app.sh steam &'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qtct.conf'
output_path = '~/.config/qt5ct/colors/matugen-colors.conf'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct.conf'
output_path = '~/.config/qt6ct/colors/matugen-colors.conf'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/matugen-colors.rasi'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/matugen-colors.css'
post_hook = 'swaync-client -rs > /dev/null'

[templates.vencord]
input_path = '~/.config/matugen/templates/vencord.css'
output_path = '~/.config/Vencord/themes/matugen-colors.css'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/matugen-colors.css'

[templates.youtube-music]
input_path = '~/.config/matugen/templates/youtube-music.css'
output_path = '~/.config/YouTube Music/matugen-colors.css'
post_hook = '~/.config/hypr/scripts/restart_app.sh youtube-music &'
