[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-fps", "60", "--transition-type", "center"]
set = true

[templates.ghostty]
input_path = '~/.config/matugen/templates/ghostty'
output_path = '~/.config/ghostty/themes/matugen-colors'
post_hook = 'pkill -SIGUSR2 ghostty'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/matugen-colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/matugen-colors.css'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland.conf'
output_path = '~/.config/hypr/source/matugen-colors.conf'
post_hook = 'hyprctl reload'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.qt5ct]
input_path = '~/.config/matugen/templates/qtct.conf'
output_path = '~/.config/qt5ct/colors/matugen-colors.conf'

[templates.qt6ct]
input_path = '~/.config/matugen/templates/qtct.conf'
output_path = '~/.config/qt6ct/colors/matugen-colors.conf'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi.rasi'
output_path = '~/.config/rofi/matugen-colors.rasi'

[templates.swaync]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/swaync/matugen-colors.css'
post_hook = 'swaync-client -rs'

[templates.vencord]
input_path = '~/.config/matugen/templates/discord.css'
output_path = '~/.config/Vencord/themes/matugen-colors.css'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/matugen-colors.css'

[templates.zed]
input_path = '~/.config/matugen/templates/zed.json'
output_path = '~/.config/zed/themes/matugen-colors.json'

#[templates.root]
#input_path = '~/.config/matugen/templates/root.css'
#output_path = '~/Documents/matugen-colors.css'
